version: '3'
services:

  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    ports:
      - "8123:8123" # HTTP-port
      - "9000:9000" # Native-port
    networks:
      - clickhouse-network

networks:
  clickhouse-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16